"""
Local golden dataset loading.

Goldens live as JSON files under ``test/data/``, generated by
``test/setup_deepeval.py``. Nothing is pushed to or pulled from a hosted
evaluation platform.
"""

import os

from deepeval.dataset import EvaluationDataset

DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data")


def load_dataset(file_name: str) -> EvaluationDataset:
    """
    Load a golden dataset from ``test/data/<file_name>.json``.

    Raises a pointed error when the file is missing, since that means the
    setup script was never run.
    """
    path = os.path.join(DATA_DIR, f"{file_name}.json")
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Golden dataset not found at {path}. "
            "Generate it first with: uv run python test/setup_deepeval.py"
        )

    dataset = EvaluationDataset()
    dataset.add_goldens_from_json_file(path)
    return dataset
